### ISSUE TITLE
not working after upgrading to 2021.5.0

### ISSUE THREAD

**Issue by divemasterjm** [evanjd/hass-logi-circle#7]
Logger: homeassistant.config
Source: custom_components/logi_circle_legacy/camera.py:8
Integration: Logi Circle (Private API) (documentation)
First occurred: 9:59:28 PM (1 occurrences)
Last logged: 9:59:28 PM

Platform error: camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 853, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 493, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/logi_circle_legacy/camera.py", line 8, in <module>
    from homeassistant.components.camera import (
ImportError: cannot import name 'CAMERA_SERVICE_SCHEMA' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)

**Comment by divemasterjm** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:671
First occurred: 10:10:59 PM (1 occurrences)
Last logged: 10:10:59 PM

Error occurred loading configuration flow for integration logi_circle: cannot import name 'LogiCircle' from 'logi_circle' (/usr/local/lib/python3.8/site-packages/logi_circle/__init__.py)

**Comment by divemasterjm** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:541
Integration: Sensor (documentation, issues)
First occurred: 9:59:29 PM (6 occurrences)
Last logged: 9:59:29 PM

Platform logi_circle_legacy does not generate unique IDs. ID 44:73:D6:0C:xx:xx-speaker_volume already exists - ignoring sensor.logi_circle_legacy_dormitorio_volume
Platform logi_circle_legacy does not generate unique IDs. ID 44:73:D6:0C:xx:xx-signal_strength_category already exists - ignoring sensor.logi_circle_legacy_dormitorio_wifi_signal_category
Platform logi_circle_legacy does not generate unique IDs. ID 44:73:D6:0C:xx:xx-streaming_mode already exists - ignoring sensor.logi_circle_legacy_dormitorio_streaming_mode
Platform logi_circle_legacy does not generate unique IDs. ID 44:73:D6:0C:xx:xx-privacy_mode already exists - ignoring sensor.logi_circle_legacy_dormitorio_privacy_mode
Platform logi_circle_legacy does not generate unique IDs. ID 44:73:D6:0C:xx:xx-last_activity_time already exists - ignoring sensor.logi_circle_legacy_dormitorio_last_activity

**Comment by divemasterjm** [comment]
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:482
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:27:40 PM (2 occurrences)
Last logged: 10:28:15 PM

Platform error camera.logi_circle_legacy - cannot import name 'CAMERA_SERVICE_SCHEMA' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)

**Comment by divemasterjm** [comment]
@evanjd Hi, any clue about?

**Comment by PsY4** [comment]
Hey o/
Got it working !

in `camera.py`, line 9 remove `CAMERA_SERVICE_SCHEMA,` from the import
next, same file, around line 40, add : 

`CAMERA_SERVICE_SCHEMA = vol.Schema(
    {
        vol.Required(ATTR_ENTITY_ID): cv.comp_entity_ids
    }
)
`

That should do the trick

[ Source : [https://gitea.ddns.net/EmEvTh/imagesdirectory-camera/commit/df5a3513f6256bd63ee07e243e58141de8c6e538](https://gitea.ddns.net/EmEvTh/imagesdirectory-camera/commit/df5a3513f6256bd63ee07e243e58141de8c6e538) ]

**Comment by navjul** [comment]
Hello, is this still working with latest HAOS version ?

I'm having this issue :

Platform error camera.logi_circle_legacy - Integration 'logi_circle_legacy' not found.
Platform error sensor.logi_circle_legacy - Integration 'logi_circle_legacy' not found.
Integration error: logi_circle_legacy - Integration 'logi_circle_legacy' not found.

Setup failed for 'logi_circle_legacy': Integration not found.
19:20:39 – (ERREUR) setup.py
Platform error: sensor - Integration 'logi_circle_legacy' not found.
19:20:39 – (ERREUR) config.py

**Comment by navjul** [comment]
@evanjd any ideas pls ?

**Comment by evanjd** [comment]
> @evanjd any ideas pls ?

I can't speak to your specific issue (failing to load the custom integration), but even if that problem were to be resolved, the Logi Circle library it depends on is no longer functioning. See issue: https://github.com/evanjd/python-logi-circle/issues/15
